module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    SEKOLAH_ADD_NEW: "SEKOLAH_ADD_NEW",
    SEKOLAH_VIEW_DETAIL: "SEKOLAH_VIEW_DETAIL",
    UPDATE_SEKOLAH: "UPDATE_SEKOLAH",
    JURUSAN_ADD_NEW: "JURUSAN_ADD_NEW",
    JURUSAN_VIEW: "JURUSAN_VIEW",
    JURUSAN_UPDATE: "JURUSAN_UPDATE",
    SKILL_ADD_NEW: "SKILL_ADD_NEW",
    SKILL_UPDATE: "SKILL_UPDATE",
    SKILL_VIEW: "SKILL_VIEW",
    ADD_PROFESI_NEW: "ADD_PROFESI_NEW",
    VIEW_PROFESI: "VIEW_PROFESI",
    UPDATE_PROFESI: "UPDATE_PROFESI",
    KAMPUS_ADD_NEW: "KAMPUS_ADD_NEW",
    KAMPUS_VIEW: "KAMPUS_VIEW", 
    KAMPUS_UPDATE: "KAMPUS_UPDATE", 
    SOAL_ADD_NEW: "SOAL_ADD_NEW",
    VERSI_ADD_NEW: "VERSI_ADD_NEW",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
  },
});
